### ISSUE TITLE
Create Towns Module System

### ISSUE THREAD

**Issue by HaedHutner** [Atherys/AtherysTowns#136]
**Description:** AtherysTowns has expanded quite a bit in its feature set since its initial creation, and now supports many different features. Users may not want to use the entire feature set, and might like to enable or disable certain functionality.

For this purpose, the features of AtherysTowns should be split up into modules, a la Nucleus, which can be configured and turned off/on independently of eachother.

**Purpose:** Quality of life improvements & ease of use

**Comment by cicetil** [comment]
This has been implemented for economy, taxes and town size automation features. Although might be good to have a module for nations as well at some point.
