### ISSUE TITLE
i am stupid. and every town i tryu to create town, it says "

### ISSUE THREAD

**Issue by Thyrus1** [Atherys/AtherysTowns#152]
**Description:** _What's wrong?_

**Reproduction Steps:** _How do we re-create it?_

**Expected Behavior:** _What should be happening?_

**Observed Behavior:** _What is happening instead?_

**Comment by AaronFoley** [comment]
@Thyrus1 please add more details to this issue.

**Comment by AaronFoley** [comment]
Duplicate of #153
