### ISSUE TITLE
"value not present" when creating Town

### ISSUE THREAD

**Issue by Thyrus1** [Atherys/AtherysTowns#153]
i do p select a
then p select b
stand in area
type /town create name
and it says no value present

**Comment by AaronFoley** [comment]
@Thyrus1 please attach a copy of your Atherys Towns Configuration, a screenshot of the error message, and the server logs when the error occurs.

**Comment by Thyrus1** [comment]
kk

**Comment by Thyrus1** [comment]
[town.txt](https://github.com/Atherys/AtherysTowns/files/5897971/town.txt)
![image](https://user-images.githubusercontent.com/56560363/106357276-27c86c80-62d3-11eb-84c4-ea006bcebc1e.png)
[latest.log](https://github.com/Atherys/AtherysTowns/files/5897973/latest.log)

**Comment by Thyrus1** [comment]
plz note, the town file is a .conf in the folder, just didnt work when i posted it so i copied it to a text document

**Comment by Thyrus1** [comment]
im confused on what that means? as i stated. im stupid.. can ya give the dummed down explanation what that means?

**Comment by Thyrus1** [comment]
any updates on this?

**Comment by LJNIC** [comment]
> any updates on this?

Oops, this was totally an issue on our end. The default configuration doesn't set a currency (it's impossible to load the currency when the config gets created, but we should look for a workaround), so there is an undocumented field for specifying the currency used by AtherysTowns. Since there was no currency set, the plugin threw an error on town creation.

Set a config field with the name `default-currency=<currency id>`, for example `default-currency=atherys:sickle`. 

Thanks for bringing this up again!

**Comment by Thyrus1** [comment]
> > any updates on this?
> 
> Oops, this was totally an issue on our end. The default configuration doesn't set a currency (it's impossible to load the currency when the config gets created, but we should look for a workaround), so there is an undocumented field for specifying the currency used by AtherysTowns. Since there was no currency set, the plugin threw an error on town creation.
> 
> Set a config field with the name `default-currency=<currency id>`, for example `default-currency=atherys:sickle`.
> 
> Thanks for bringing this up again!

where would i put this in the config? at the bottom?

**Comment by LJNIC** [comment]
Any place at the top level (not under a subsection).

**Comment by Thyrus1** [comment]
> Any place at the top level (not under a subsection).

okie dokie, ty!

**Comment by Thyrus1** [comment]
> Any place at the top level (not under a subsection).

so, for currency, its like "maxwell123 has: 400 (whatever the name of the currency is)" is what i put after the default currency config edit?

**Comment by Thyrus1** [comment]
i.e. if its default-currency=dogs
maxwell123 had: 400 dogs

**Comment by LJNIC** [comment]
That's the idea, but the exact name might depend on the plugin. It looks like XConomy, if you're still using it, only has a single currency with the ID "xconomy".
