### ISSUE TITLE
says economy not enabled when it is, and /town increase name amount isnt working

### ISSUE THREAD

**Issue by Thyrus1** [Atherys/AtherysTowns#155]
**Description:** _What's wrong?_
ays economy not enabled when it is, and /town increase name amount isnt working and /town deposit isnt working
**Reproduction Steps:** _How do we re-create it?_
ftb revelation, 1.12.2
**Expected Behavior:** _What should be happening?_
as their respected commands work
**Observed Behavior:** _What is happening instead?_
they dont work
![image_2021-04-25_200521](https://user-images.githubusercontent.com/56560363/116014102-903c9680-a601-11eb-83e3-aef4e046ca3f.png)
![image_2021-04-25_200530](https://user-images.githubusercontent.com/56560363/116014107-9599e100-a601-11eb-80f2-636c3095aa58.png)
![image_2021-04-25_200549](https://user-images.githubusercontent.com/56560363/116014113-a0ed0c80-a601-11eb-9a2f-c627fdb50a03.png)

**Comment by Thyrus1** [comment]
![image_2021-04-25_201948](https://user-images.githubusercontent.com/56560363/116014494-95024a00-a603-11eb-964f-95b63e565884.png)
![image](https://user-images.githubusercontent.com/56560363/116014504-9a5f9480-a603-11eb-9207-48a513288258.png)

**Comment by LJNIC** [comment]
Nice find. Send a log, your configuration might have an error in it. 

Download the new version here: https://repo.atherys.com/releases/com/atherys/AtherysTowns/2.1.0/AtherysTowns-2.1.0.jar

**Comment by LJNIC** [comment]
Also, it might be easier if you join the discord https://discord.com/invite/aa2EVsg and ask in #plugin-support.

**Comment by Thyrus1** [comment]
didnt know there was a discord
