### ISSUE TITLE
Can't create town. Error in console!

### ISSUE THREAD

**Issue by imbennji** [Atherys/AtherysTowns#158]
I basically tried to create a town with two plot points select within one chunk and it gave me a big error and this is the error! any help would be good!
![2022-02-19_16 42 48](https://user-images.githubusercontent.com/75706138/154824027-59572aae-e9a6-48e0-9b7f-65f7ac3e8e8d.png)

**Comment by LJNIC** [comment]
I believe this is more of a problem with the economy plugin but we should handle it gracefully. This happened because Towns couldn't fetch the economy account corresponding to the player's UUID.
